package:
  name: pipits
  version: "2.5"

source:
  url: https://github.com/hsgweon/pipits/archive/2.5.tar.gz
  sha256: 12111f9f32b3ad5da67735b2248f55c32b190fda10b5bc869d1baf6312be509f

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3
    - setuptools
  run:
    - python >=3
    - pispino >=1.1
    - vsearch
    - fastx_toolkit
    - hmmer
    - itsx
    - biom-format
    - rdptools
    - numpy ==1.15.0
    - pandas
    - progressbar2
    - requests
    - seqkit

test:
  commands:
    - pipits_funits -h > /dev/null
    - pipits_process -h > /dev/null

about:
  home: https://github.com/hsgweon/pipits
  summary: "PIPITS: An automated pipeline for analyses of fungal internal transcribed spacer (ITS) sequences from the Illumina sequencing platform"
  license: GNU General Public License v3.0
  license_family: GPL3
